const initialValues = {
  movingAndNonMovingItemsLists: [],
  movingAndNonMovingItemsStatus: null,
  categoriesStatus: null,
  categoriesList: [],
  groupStatus: null,
  groupList: [],
  classStatus: null,
  classList: [],
  batchDetailsForReturn: [],
  batchDetailsForReturnStatus: null,
  drugStoreStatus: null,
  drugStoreDetails: [],
  allReturnRequestStatus: null,
  allReturnRequestDetails: [],
  singleReturnStatus: null,
  singleReturnDetails: [],
  singleReturnDetailStatus: null,
  singleReturnDetailsInfo: [],
  wareHouseStatus: null,
  wareHouseDetails: [],
  remarksStatus: null,
  remarksDetails: [],
  orderRequestStatus: null,
  pickupPersonStatus: null,
  pickupPersonDetails: [],
  wareHouseStatusModal: null,
  returnModePagination: {},
  returnRequestsPagination: {},
  getWarehouseItemsStatus: null,
  getWarehouseItemsData: [],
  wareHouseName: "",
  orderLink:[],
  orderLinkStatus:true
}
export default initialValues;