const initialValues = {
    singleOneOrderItemStatus: null,
    singleOneOrderItemData: null,
    strengthStatus: null,
    strengthList: null,
    forecastStatus: null,
    movingNonMovingStatus: null,
    movingNonMovingList: null,
    agentStatus:null,
    agentData:null,
    installmentStatus:null,
    installmentList:null,
    createInstallmentStatus:null,
    msdStockStatus:null,
    msdStockList:null,
    msdStockDateStatus:null,
    msdStockDateList:null,
    insitutionalStatus:null,
    insitutionalDateList:null,
    insitutionalDateStatus:null,
    insitutionalList:null,
    putOrderStatus:null,
    orderQuantityStatus:null,
    placeOrderStatus:null,
    upcomingOrderStatus:null,
    upcomingOrderData:null,
    estimationStatus: null,
    estimationData:null,
    estimationStatusMonthly: null,
    estimationDataMonthly:null,
    consumptionsStatusMonthly: null,
    consumptionsDataMonthly:null,
    consumptionsStatus: null,
    consumptionsData:null,
    approvalStatus:null,
    batchStatus:null,
    batchData:null,
    dueStatus:null,
    dueData:null,
    orderStatus:null,
    orderData:null,
    historyStatus:null,
    historyData:null,
    installmentUpdateStatus:null,
    installmentDeleteStatus:null,
}
export default initialValues
